version: '3'
services:
    trans-srv:
        build: transaction-server
        depends_on:
            - postgres
        restart: "no"
        ports:
            - ${TRANS_SRV_PORT}:5555
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=${PG_USERNAME}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_DB=${PG_DATABASE}
        ports:
            - ${PG_PORT}:5432
    adminer-pg:
        image: michalhosna/adminer:4.7.0
        depends_on:
            - postgres
        restart: always
        ports:
            - ${ADMINER_PG_PORT}:8080
        environment:
            - ADMINER_DRIVER=pgsql
            - ADMINER_DB=docker
            - ADMINER_SERVER=postgres
            - ADMINER_USERNAME=${PG_USERNAME}
            - ADMINER_PASSWORD=${PG_PASSWORD}
            - ADMINER_AUTOLOGIN=0
    mongo:
        image: mongo
        restart: always
        ports:
            - ${MONGO_PORT}:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    adminer-mongo:
        image: dockette/adminer:full-php5
        depends_on:
            - mongo
        restart: always
        ports:
            - ${ADMINER_MONGO_PORT}:80
    workload-gen:
            build: wl_generator
    transaction-server-quart:
            build: transaction-server-quart
            depends_on:
                    - postgres
                    - mongo
            restart: unless-stopped
            ports:
                    - 5000:5000
    frontend:
        build: frontend
        depends_on:
            - mongo
        restart: "no"
        ports:
            - ${FRONTEND_PORT}:5050
