version: '3'
services:
    postgres:
        build: db-write
        restart: on-failure
        environment:
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASS}
        ports:
            - ${PG_PORT}:5432
    adminer:
        image: michalhosna/adminer:4.7.0
        depends_on:
            - postgres
        restart: on-failure
        ports:
            - ${ADMINER_PORT}:8080
        environment:
            - ADMINER_DRIVER=pgsql
            - ADMINER_DB=docker
            - ADMINER_SERVER=postgres
            - ADMINER_USERNAME=${PG_USER}
            - ADMINER_PASSWORD=${PG_PASS}
            - ADMINER_AUTOLOGIN=1
